version: '3.3'

services:
  web:
    build: .
    command: >
      sh -c "python movienager/manage.py collectstatic --noinput && 
             python movienager/manage.py migrate &&
             python movienager/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/movienager/
    expose:
      - 8000
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file: .env-db
    ports:
      - 5433:5432

volumes:
  postgres_data:
