# Generated by Django 2.2.12 on 2020-04-16 09:45

from django.db import migrations, models
import django.db.models.deletion
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200415_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='directed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director', to='movies.Person', verbose_name='Directed by'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to=movies.models.poster_directory_path, verbose_name='Poster'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='prod_year',
            field=models.IntegerField(verbose_name='Production year'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='short_desc',
            field=models.CharField(max_length=512, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='starring',
            field=models.ManyToManyField(related_name='actors', to='movies.Person', verbose_name='Starring'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Title'),
        ),
    ]
