# Generated by Django 2.2.12 on 2020-04-17 08:17

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200416_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, upload_to=movies.models.person_photo_directory_path, verbose_name='Photo'),
        ),
    ]
